version: '3.3'

services:

    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=8.11.1
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=production
                - YARN=false
        volumes:
            - ../:/opt/app
        entrypoint: run-nodock "node index.js"
        tty: true

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_HOST=localhost
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"

    workspace:
        build:
            context: ./workspace
            args:
                - NODE_VERSION=latest
                - TZ=UTC
        volumes:
            - ../:/opt/app
            